apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: rudwns273/springboot:01-18-00-20-29
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://tempo.grafana.svc.cluster.local:4317"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_SERVICE_NAME
          value: "demo"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED
          value: "false"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: MONGODB_URL
          value: "mongodb://database:database@mongo-psmdb-db-rs0.mongo.svc.cluster.local:27017/company?authSource=admin&readPreference=secondaryPreferred"