spring:
  data:
    mongodb:
      #uri: mongodb://database:database@mongo-psmdb-db-rs0.mongo.svc.cluster.local:27017/company?authSource=admin&readPreference=primary
      #uri: mongodb://database:database@localhost:27017/company?authSource=admin&readPreference=secondaryPreferred
      uri : ${MONGODB_URL}

# OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc
# OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4317
# OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
# OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces

logging:
  level:
    root: ${LOG_LEVEL}